# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.7
  hooks:
  - id: clang-format
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: local
  hooks:
    - id: custom-python-hook
      name: slangpy hooks
      entry: python tools/local_precommit.py
      language: python

exclude: |
  (?x)^(
      .*\.ipynb|
      build/.*|
      external/.*|
      src/sgl/stl/.*|
      src/slangpy_ext/py_doc.h|
      docs/generated/.*|
      tools/run_clang_format.py|
  )$
