# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Build and validate the SlangPy documentation."""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Sequence

import griffe

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised on Python 3.9/3.10
    import tomli as tomllib  # pyright: ignore[reportMissingImports]


PROJECT_DIR = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_DIR / "docs"
GENERATED_API_PATH = DOCS_DIR / "generated" / "api.rst"
TUTORIAL_SOURCE_DIR = PROJECT_DIR / "samples" / "tutorials"
TUTORIAL_OUTPUT_DIR = DOCS_DIR / "src" / "tutorials"
DEFAULT_HTML_OUTPUT_DIR = DOCS_DIR / "_build" / "html"
PUBLIC_API_PATH = DOCS_DIR / "public_api.toml"
API_INVENTORY_PATH = DOCS_DIR / "api" / "api.json"
API_COVERAGE_BASELINE_PATH = DOCS_DIR / "api" / "coverage-baseline.json"
RENDERED_API_DIR = DOCS_DIR / "generated" / "api"
AGENT_SITE_SOURCE_DIR = DOCS_DIR / "generated" / "site"
GENERATED_PAGE_HEADER = ".. This file is generated by tools/docs.py. Do not edit it directly."
CURATED_LLMS_PAGES = (
    (
        "Start here",
        (
            ("Getting started", "index.md", "Install SlangPy and choose a learning path."),
            (
                "Your first function",
                "src/basics/firstfunctions.md",
                "Load and call a Slang function from Python.",
            ),
            ("Tensors", "src/basics/tensors.md", "Create and operate on SlangPy tensors."),
            (
                "Broadcasting",
                "src/basics/broadcasting.md",
                "Understand automatic vectorization and broadcasting.",
            ),
            (
                "Automatic differentiation",
                "src/autodiff/autodiff.md",
                "Differentiate Slang functions.",
            ),
            (
                "PyTorch integration",
                "src/autodiff/pytorch.md",
                "Connect SlangPy kernels to PyTorch autograd.",
            ),
            (
                "Compute shader tutorial",
                "src/tutorials/compute_shader.md",
                "Use the low-level compute API.",
            ),
            (
                "Image I/O tutorial",
                "src/tutorials/image_io_and_manipulation.md",
                "Load, process, and write images.",
            ),
        ),
    ),
    (
        "API reference",
        (
            ("API overview", "src/api_reference.md", "Navigate the reviewed public API."),
            (
                "Functional API",
                "generated/api/functional-api.md",
                "Tensor, Module, Function, and their members.",
            ),
            (
                "Additional SlangPy API",
                "generated/api/slangpy.md",
                "Supporting high-level and functional runtime types.",
            ),
            ("Core", "generated/api/core.md", "Fundamental data and utility types."),
            ("Constants", "generated/api/constants.md", "Public package constants."),
            ("Logging", "generated/api/logging.md", "Logging levels and outputs."),
            ("Windowing", "generated/api/windowing.md", "Windows and input events."),
            ("Platform", "generated/api/platform.md", "Operating-system services."),
            ("Threading", "generated/api/threading.md", "Thread utilities."),
            (
                "Device and graphics",
                "generated/api/device.md",
                "Devices, resources, commands, pipelines, reflection, and ray tracing.",
            ),
            ("Application", "generated/api/application.md", "Application and window helpers."),
            ("Math", "generated/api/math.md", "Vectors, matrices, quaternions, and functions."),
            ("UI", "generated/api/ui.md", "Immediate-mode user-interface types."),
            (
                "Utilities",
                "generated/api/utilities.md",
                "Texture loading and external tool integration.",
            ),
            (
                "Extension author API",
                "generated/api/extension-api.md",
                "Interfaces for custom Python-to-Slang bindings.",
            ),
        ),
    ),
    (
        "Machine-readable data",
        (
            ("Public API inventory", "api/api.json", "Versioned signatures and documentation."),
            (
                "Documentation coverage",
                "api/coverage.json",
                "Versioned per-symbol documentation gaps and status.",
            ),
        ),
    ),
    (
        "Contributing",
        (
            ("Developer guide", "src/developer_guide.md", "Repository architecture and workflow."),
            (
                "Documentation builds",
                "src/developer_guide/compiling.md",
                "Build, validate, and update documentation outputs.",
            ),
            ("Testing", "src/developer_guide/testing.md", "Run SlangPy test suites."),
            ("Coding style", "src/developer_guide/coding_style.md", "Project style conventions."),
        ),
    ),
)

FORBIDDEN_DATA_NAMES = {
    "slangpy.SGL_BUILD_TYPE",
    "slangpy.SGL_GIT_VERSION",
    "slangpy.SHADER_PATH",
    "slangpy.build_dir",
    "slangpy.package_dir",
}
ALLOWED_DATA_NAMES = {
    "slangpy.ALL_LAYERS",
    "slangpy.ALL_MIPS",
    "slangpy.SGL_VERSION_MAJOR",
    "slangpy.SGL_VERSION_MINOR",
    "slangpy.SGL_VERSION_PATCH",
    "slangpy.SGL_VERSION",
}

WINDOWS_ABSOLUTE_PATH_RE = re.compile(r"(?<![A-Za-z0-9])[A-Za-z]:[\\/]")
POSIX_ABSOLUTE_PATH_RE = re.compile(
    r"(?<![:A-Za-z0-9])/(?:home|Users|tmp|var|opt|workspace|build)(?:/|\b)"
)
BUILD_PATH_RE = re.compile(r"(?:^|[\"'])(?:build|cmake-build-[^/\\]+)[/\\]")
MEMORY_ADDRESS_RE = re.compile(r"\bat 0x[0-9a-fA-F]{6,}\b")
OBJECT_REPRESENTATION_RE = re.compile(
    r"<(?:[^>]*\bobject\b[^>]*|[^>]*\b(?:built-in )?function\b[^>]*)>"
)


class DocumentationError(RuntimeError):
    """Raised when documentation preparation or validation fails."""


@dataclass(frozen=True)
class PublicApiSection:
    """One ordered section in the reviewed public API contract."""

    id: str
    title: str
    audience: str
    names: tuple[str, ...] = ()
    patterns: tuple[str, ...] = ()


@dataclass(frozen=True)
class PublicApiConfig:
    """Reviewed public API configuration loaded from TOML."""

    schema_version: int
    package: str
    sections: tuple[PublicApiSection, ...]
    version_source: str | None = None
    package_version: str | None = None
    show_missing_documentation: bool = False


@dataclass
class DocumentationRecord:
    """Normalized documentation attached to an API symbol."""

    summary: str = ""
    body: str = ""
    parameters: dict[str, str] = field(default_factory=dict)
    returns: str = ""
    raises: list[str] = field(default_factory=list)
    status: str = "missing"


@dataclass
class SourceReference:
    """Repository-relative source location for an API symbol."""

    path: str
    line: int | None = None


@dataclass
class ApiSymbol:
    """Stable, renderer-independent representation of one public symbol."""

    name: str
    canonical_name: str
    kind: str
    section: str
    audience: str
    signatures: list[str] = field(default_factory=list)
    aliases: list[str] = field(default_factory=list)
    documentation: DocumentationRecord = field(default_factory=DocumentationRecord)
    source: SourceReference | None = None


@dataclass
class ApiInventory:
    """Versioned structured public API snapshot."""

    schema_version: int
    package_version: str
    sections: list[dict[str, str]]
    symbols: list[ApiSymbol]


@dataclass
class CoverageSymbol:
    """Mechanical documentation coverage result for one public symbol."""

    name: str
    status: str
    missing_parameters: list[str] = field(default_factory=list)
    requires_return: bool = False
    return_documented: bool = False
    has_examples: bool = False


@dataclass
class CoverageReport:
    """Versioned documentation coverage report."""

    schema_version: int
    package_version: str
    counts: dict[str, int]
    documented: int
    score: int
    symbols: list[CoverageSymbol]


@dataclass(frozen=True)
class RepositoryReference:
    """One repository-relative source, test, binding, or example location."""

    path: str
    line: int


@dataclass
class DocumentationTask:
    """One incomplete public documentation task for humans or agents."""

    name: str
    section: str
    audience: str
    status: str
    missing_fields: list[str]
    source: SourceReference | None = None


@dataclass(frozen=True)
class _ObjectPair:
    """Source and stub views of the same published object."""

    published_name: str
    canonical_name: str
    source: Any | None
    stub: Any | None


class _StaticPackage:
    """Load Python sources and generated stubs without importing the package."""

    def __init__(self, package_root: Path, package_name: str) -> None:
        super().__init__()
        self.package_root = package_root.resolve()
        self.package_name = package_name
        try:
            self.source = griffe.load(
                package_name,
                search_paths=[self.package_root.parent],
                allow_inspection=False,
                resolve_aliases=True,
                docstring_parser="sphinx",
            )
        except Exception as exc:
            raise DocumentationError(
                f"Could not statically load package '{package_name}' from {package_root}"
            ) from exc

        self.stub_modules: dict[str, Any] = {}
        for path in sorted(self.package_root.rglob("*.pyi")):
            relative = path.relative_to(self.package_root)
            if path.name == "__init__.pyi":
                suffix = relative.parent.parts
            else:
                suffix = (*relative.parent.parts, path.stem)
            module_name = ".".join((package_name, *suffix))
            self.stub_modules[module_name] = griffe.visit(
                module_name,
                path,
                path.read_text(encoding="utf-8"),
                docstring_parser="sphinx",
            )

    @staticmethod
    def _final_target(obj: Any | None) -> Any | None:
        if obj is None:
            return None
        if getattr(obj, "is_alias", False):
            try:
                return obj.final_target
            except Exception:
                return None
        return obj

    def source_object(self, name: str) -> Any | None:
        """Return a source object for a fully qualified published name."""
        parts = name.split(".")
        if not parts or parts[0] != self.package_name:
            return None
        current: Any = self.source
        for part in parts[1:]:
            current = self._final_target(current)
            if current is None:
                return None
            current = getattr(current, "members", {}).get(part)
            if current is None:
                return None
        return self._final_target(current)

    def stub_object(self, name: str, seen: set[str] | None = None) -> Any | None:
        """Return a stub object, resolving aliases between generated stub modules."""
        if seen is None:
            seen = set()
        if name in seen:
            return None
        seen.add(name)

        parts = name.split(".")
        for index in range(len(parts), 0, -1):
            module_name = ".".join(parts[:index])
            module = self.stub_modules.get(module_name)
            if module is None:
                continue
            current: Any = module
            for part in parts[index:]:
                current = getattr(current, "members", {}).get(part)
                if current is None:
                    break
            if current is None:
                continue
            if getattr(current, "is_alias", False):
                return self.stub_object(str(current.target_path), seen)
            return current
        return None

    def object_pair(self, published_name: str) -> _ObjectPair | None:
        """Return the combined source/stub representation for a published name."""
        source = self.source_object(published_name)
        canonical_name = str(getattr(source, "canonical_path", published_name))
        stub = self.stub_object(published_name)
        if stub is None:
            stub = self.stub_object(canonical_name)
        if source is None and stub is None:
            return None
        if source is None:
            canonical_name = str(getattr(stub, "canonical_path", published_name))
        return _ObjectPair(published_name, canonical_name, source, stub)

    def discover_public_names(self) -> list[str]:
        """Return statically reachable public-looking package-level names."""
        discovered: set[str] = set()
        visited_modules: set[str] = set()

        def visit_module(module: Any, published_path: str) -> None:
            target = self._final_target(module)
            if target is None:
                return
            canonical_path = str(getattr(target, "canonical_path", published_path))
            if canonical_path in visited_modules:
                return
            visited_modules.add(canonical_path)
            exports = getattr(target, "exports", None)
            explicit_exports = {str(export) for export in exports} if exports is not None else None
            for member_name, member in getattr(target, "members", {}).items():
                if member_name.startswith("_"):
                    continue
                if explicit_exports is not None and member_name not in explicit_exports:
                    continue
                member_path = f"{published_path}.{member_name}"
                member_target = self._final_target(member)
                if member_target is None:
                    continue
                if getattr(member_target, "is_module", False) and str(
                    getattr(member_target, "canonical_path", "")
                ).startswith(f"{self.package_name}."):
                    visit_module(member_target, member_path)
                else:
                    discovered.add(member_path)

        visit_module(self.source, self.package_name)
        return sorted(discovered)


def load_public_api(path: Path) -> PublicApiConfig:
    """Load and validate a public API contract from TOML."""
    if not path.is_file():
        raise DocumentationError(f"Public API contract does not exist: {path}")
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        sections = tuple(
            PublicApiSection(
                id=str(section["id"]),
                title=str(section["title"]),
                audience=str(section["audience"]),
                names=tuple(str(name) for name in section.get("names", [])),
                patterns=tuple(str(pattern) for pattern in section.get("patterns", [])),
            )
            for section in data["sections"]
        )
        show_missing_documentation = data.get("show_missing_documentation", False)
        if not isinstance(show_missing_documentation, bool):
            raise TypeError("show_missing_documentation must be a boolean")
        config = PublicApiConfig(
            schema_version=int(data["schema_version"]),
            package=str(data["package"]),
            version_source=data.get("version_source"),
            package_version=data.get("package_version"),
            show_missing_documentation=show_missing_documentation,
            sections=sections,
        )
    except (KeyError, TypeError, ValueError, tomllib.TOMLDecodeError) as exc:
        raise DocumentationError(f"Invalid public API contract: {path}") from exc

    if config.schema_version != 1:
        raise DocumentationError(f"Unsupported public API schema version: {config.schema_version}")
    if not config.sections or len({section.id for section in config.sections}) != len(
        config.sections
    ):
        raise DocumentationError("Public API sections must be non-empty and have unique IDs")
    if not re.fullmatch(r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*", config.package):
        raise DocumentationError(f"Invalid public API package name: {config.package}")
    reviewed_names: dict[str, str] = {}
    for section in config.sections:
        if not section.id or not section.title:
            raise DocumentationError("Public API section IDs and titles must be non-empty")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", section.id):
            raise DocumentationError(
                f"Public API section ID is not a stable URL slug: {section.id}"
            )
        if section.audience not in {"user", "extension-author"}:
            raise DocumentationError(
                f"Unsupported audience in section '{section.id}': {section.audience}"
            )
        for name in section.names:
            if not name.startswith(f"{config.package}."):
                raise DocumentationError(
                    f"Public API name '{name}' is outside package '{config.package}'"
                )
            if name in reviewed_names:
                raise DocumentationError(
                    f"Public API name '{name}' occurs in both '{reviewed_names[name]}' "
                    f"and '{section.id}'"
                )
            reviewed_names[name] = section.id
        for pattern in section.patterns:
            try:
                re.compile(pattern)
            except re.error as exc:
                raise DocumentationError(
                    f"Invalid public API pattern in section '{section.id}': {pattern}"
                ) from exc
    return config


def _package_version(config: PublicApiConfig, package_root: Path) -> str:
    if config.package_version is not None:
        return config.package_version
    if config.version_source is None:
        return "unknown"
    version_path = package_root.parent / config.version_source
    if not version_path.is_file():
        raise DocumentationError(f"Package version source does not exist: {version_path}")
    text = version_path.read_text(encoding="utf-8")
    components = []
    for component in ("MAJOR", "MINOR", "PATCH"):
        match = re.search(rf"^#define SGL_VERSION_{component} (\d+)$", text, re.MULTILINE)
        if match is None:
            raise DocumentationError(f"Could not read SGL_VERSION_{component} from {version_path}")
        components.append(match.group(1))
    return ".".join(components)


def _doc_record(*objects: Any | None) -> DocumentationRecord:
    raw = ""
    for obj in objects:
        docstring = getattr(obj, "docstring", None)
        value = getattr(docstring, "value", "") if docstring is not None else ""
        if value and str(value).strip():
            raw = str(value).replace("\r\n", "\n").strip()
            break
    if not raw:
        return DocumentationRecord()
    if raw.strip().upper() == "N/A":
        return DocumentationRecord(status="placeholder")
    raw = re.sub(r"``([^`]+)``\(\)", r"``\1()``", raw)

    parameters: dict[str, str] = {}
    raises: list[str] = []
    returns = ""
    narrative: list[str] = []
    for line in raw.splitlines():
        stripped = line.strip()
        parameter = re.match(r":param\s+([^:]+):\s*(.*)", stripped)
        returned = re.match(r":returns?:\s*(.*)", stripped)
        raised = re.match(r":raises?\s+([^:]+):\s*(.*)", stripped)
        if parameter:
            parameters[parameter.group(1)] = parameter.group(2).strip()
        elif returned:
            returns = returned.group(1).strip()
        elif raised:
            raises.append(f"{raised.group(1)}: {raised.group(2).strip()}".rstrip(": "))
        elif not stripped.startswith(":type") and not stripped.startswith(":rtype"):
            narrative.append(line.rstrip())

    narrative_text = "\n".join(narrative).strip()
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", narrative_text) if part.strip()]
    summary = " ".join(paragraphs[0].splitlines()) if paragraphs else ""
    body = "\n\n".join(paragraphs[1:])
    status = "complete" if body or parameters or returns or raises else "summary"
    return DocumentationRecord(summary, body, parameters, returns, raises, status)


def _overloads(parent: Any | None, name: str) -> list[Any]:
    if parent is None:
        return []
    overloads = getattr(parent, "overloads", {})
    return list(overloads.get(name, []))


def _member(parent: Any | None, name: str) -> Any | None:
    if parent is None:
        return None
    try:
        members = parent.all_members
    except (AttributeError, KeyError):
        members = getattr(parent, "members", {})
    obj = members.get(name)
    return _StaticPackage._final_target(obj)


def _signatures(obj: Any | None, overloads: list[Any] | None = None) -> list[str]:
    functions = overloads or []
    if not functions and obj is not None:
        functions = list(getattr(obj, "overloads", []) or []) or [obj]
    result: list[str] = []
    for function in functions:
        signature = getattr(function, "signature", None)
        if callable(signature):
            result.append(str(signature()))
    return list(dict.fromkeys(result))


def _kind(obj: Any | None, name: str) -> str:
    if name == "__init__":
        return "constructor"
    if obj is None:
        return "method"
    if getattr(obj, "is_class", False):
        return "class"
    labels = set(getattr(obj, "labels", set()))
    if "property" in labels:
        return "property"
    if "staticmethod" in labels:
        return "staticmethod"
    if "classmethod" in labels:
        return "classmethod"
    if getattr(obj, "is_function", False):
        parent = getattr(obj, "parent", None)
        return "function" if getattr(parent, "is_module", False) else "method"
    return "attribute"


def _source_reference(obj: Any | None, repository_root: Path) -> SourceReference | None:
    if obj is None:
        return None
    filepath = getattr(obj, "filepath", None)
    if not isinstance(filepath, Path) or not filepath.is_file():
        return None
    line = getattr(obj, "lineno", None)
    if filepath.suffix == ".py" and isinstance(line, int):
        line_count = len(filepath.read_text(encoding="utf-8").splitlines())
        if line > line_count:
            return None
    try:
        relative = filepath.resolve().relative_to(repository_root.resolve()).as_posix()
    except ValueError:
        return None
    return SourceReference(relative, line if isinstance(line, int) else None)


def _class_symbols(
    pair: _ObjectPair,
    section: PublicApiSection,
    repository_root: Path,
    published_class_canonical_names: set[str],
) -> list[ApiSymbol]:
    source = pair.source
    stub = pair.stub
    documentation = _doc_record(source, stub)
    source_reference = _source_reference(source, repository_root) or _source_reference(
        stub, repository_root
    )
    constructor_overloads = _overloads(stub, "__init__") or _overloads(source, "__init__")
    constructor = _member(stub, "__init__")
    if constructor is None:
        constructor = _member(source, "__init__")
    class_signatures = [
        signature.replace("__init__", pair.published_name.rsplit(".", 1)[-1], 1)
        for signature in _signatures(constructor, constructor_overloads)
    ]
    symbols = [
        ApiSymbol(
            name=pair.published_name,
            canonical_name=pair.canonical_name,
            kind="class",
            section=section.id,
            audience=section.audience,
            signatures=class_signatures,
            documentation=documentation,
            source=source_reference,
        )
    ]

    member_names: set[str] = set()
    for parent in (source, stub):
        if parent is None:
            continue
        direct_members = getattr(parent, "members", {})
        member_names.update(direct_members)
        try:
            inherited_members = parent.all_members
        except (AttributeError, KeyError):
            inherited_members = {}
        for name, member in inherited_members.items():
            if name in direct_members:
                continue
            canonical_path = str(getattr(member, "canonical_path", ""))
            declaring_class = canonical_path.rsplit(".", 1)[0]
            if declaring_class not in published_class_canonical_names:
                member_names.add(name)
        member_names.update(getattr(parent, "overloads", {}))

    allowed_special = {
        "__call__",
        "__enter__",
        "__exit__",
        "__getitem__",
        "__init__",
        "__iter__",
        "__len__",
        "__repr__",
        "__setitem__",
        "__str__",
    }
    ordered_names = sorted(
        (name for name in member_names if not name.startswith("_") or name in allowed_special),
        key=lambda name: (name != "__init__", name),
    )
    for name in ordered_names:
        source_member = _member(source, name)
        stub_member = _member(stub, name)
        overloads = _overloads(stub, name) or _overloads(source, name)
        representative = source_member
        if representative is None:
            representative = stub_member
        if representative is None and overloads:
            representative = overloads[0]
        if representative is None:
            continue
        canonical_name = str(
            getattr(
                source_member if source_member is not None else stub_member,
                "canonical_path",
                f"{pair.canonical_name}.{name}",
            )
        )
        symbols.append(
            ApiSymbol(
                name=f"{pair.published_name}.{name}",
                canonical_name=canonical_name,
                kind=_kind(representative, name),
                section=section.id,
                audience=section.audience,
                signatures=_signatures(
                    stub_member if stub_member is not None else source_member,
                    overloads,
                ),
                documentation=_doc_record(source_member, stub_member, *overloads),
                source=_source_reference(source_member, repository_root)
                or _source_reference(stub_member, repository_root)
                or _source_reference(representative, repository_root),
            )
        )
    return symbols


def build_inventory(config: PublicApiConfig, package_root: Path) -> ApiInventory:
    """Build a structured inventory from static Python sources and generated stubs."""
    package = _StaticPackage(package_root, config.package)
    discovered = package.discover_public_names()
    selected: set[str] = set()
    selected_pairs: list[tuple[_ObjectPair, PublicApiSection]] = []

    for section in config.sections:
        section_names = list(section.names)
        for pattern in section.patterns:
            section_names.extend(name for name in discovered if re.fullmatch(pattern, name))
        for name in dict.fromkeys(section_names):
            if name in selected:
                continue
            pair = package.object_pair(name)
            if pair is None:
                raise DocumentationError(
                    f"Public API symbol '{name}' from section '{section.id}' was not found"
                )
            selected.add(name)
            selected_pairs.append((pair, section))

    published_class_canonical_names = {
        pair.canonical_name
        for pair, _section in selected_pairs
        if getattr(pair.source if pair.source is not None else pair.stub, "is_class", False)
    }
    symbols: list[ApiSymbol] = []
    for pair, section in selected_pairs:
        representative = pair.source if pair.source is not None else pair.stub
        if getattr(representative, "is_class", False):
            symbols.extend(
                _class_symbols(
                    pair,
                    section,
                    package_root.parent,
                    published_class_canonical_names,
                )
            )
        else:
            symbols.append(
                ApiSymbol(
                    name=pair.published_name,
                    canonical_name=pair.canonical_name,
                    kind=_kind(representative, pair.published_name.rsplit(".", 1)[-1]),
                    section=section.id,
                    audience=section.audience,
                    signatures=_signatures(pair.stub if pair.stub is not None else pair.source),
                    documentation=_doc_record(pair.source, pair.stub),
                    source=_source_reference(pair.source, package_root.parent)
                    or _source_reference(pair.stub, package_root.parent),
                )
            )

    inventory = ApiInventory(
        schema_version=1,
        package_version=_package_version(config, package_root),
        sections=[
            {"id": section.id, "title": section.title, "audience": section.audience}
            for section in config.sections
        ],
        symbols=symbols,
    )
    return normalize_inventory(inventory, package_root.parent)


def normalize_inventory(inventory: ApiInventory, repository_root: Path) -> ApiInventory:
    """Normalize ordering, aliases, paths, and repeated values in an inventory."""
    del repository_root  # Paths are made relative while symbols are extracted.
    aliases_by_canonical: dict[str, set[str]] = {}
    for symbol in inventory.symbols:
        aliases_by_canonical.setdefault(symbol.canonical_name, set()).add(symbol.name)
    for symbol in inventory.symbols:
        symbol.signatures = list(dict.fromkeys(symbol.signatures))
        symbol.aliases = sorted(aliases_by_canonical[symbol.canonical_name] - {symbol.name})
        if symbol.source is not None:
            symbol.source.path = symbol.source.path.replace("\\", "/")
    return inventory


def _inventory_text(inventory: ApiInventory) -> str:
    return json.dumps(asdict(inventory), indent=2, ensure_ascii=True) + "\n"


def _inventory_problems(text: str) -> list[str]:
    problems: list[str] = []
    checks = {
        "Windows absolute path": WINDOWS_ABSOLUTE_PATH_RE,
        "POSIX absolute path": POSIX_ABSOLUTE_PATH_RE,
        "build path": BUILD_PATH_RE,
        "memory address": MEMORY_ADDRESS_RE,
        "object representation": OBJECT_REPRESENTATION_RE,
    }
    for label, pattern in checks.items():
        if pattern.search(text):
            problems.append(label)
    if "local changes" in text.lower() or "branch:" in text.lower():
        problems.append("local Git description")
    return problems


def write_inventory(inventory: ApiInventory, output: Path) -> None:
    """Write an inventory only when its normalized JSON content changes."""
    text = _inventory_text(inventory)
    problems = _inventory_problems(text)
    if problems:
        raise DocumentationError(
            "API inventory contains environment-dependent data: " + ", ".join(problems)
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        output.write_text(text, encoding="utf-8")


def inventory_command(config_path: Path, package_root: Path, output: Path, check: bool) -> None:
    """Generate or check the structured public API snapshot."""
    config = load_public_api(config_path)
    inventory = build_inventory(config, package_root)
    text = _inventory_text(inventory)
    problems = _inventory_problems(text)
    if problems:
        raise DocumentationError(
            "API inventory contains environment-dependent data: " + ", ".join(problems)
        )
    if check:
        if not output.is_file() or output.read_text(encoding="utf-8") != text:
            raise DocumentationError(
                f"API inventory is missing or stale: {output}. Run 'python tools/docs.py inventory'."
            )
        action = "Validated"
    else:
        write_inventory(inventory, output)
        action = "Wrote"
    placeholder_count = sum(
        symbol.documentation.status in {"missing", "placeholder"} for symbol in inventory.symbols
    )
    print(
        f"{action} API inventory at {output}: {len(inventory.symbols)} symbols, "
        f"{placeholder_count} missing or placeholder documentation records"
    )


def report_unclassified(config_path: Path, package_root: Path) -> list[str]:
    """Print and return reachable public-looking names outside the reviewed contract."""
    config = load_public_api(config_path)
    package = _StaticPackage(package_root, config.package)
    discovered = package.discover_public_names()

    def classified(name: str) -> bool:
        return any(
            name in section.names
            or any(re.fullmatch(pattern, name) for pattern in section.patterns)
            for section in config.sections
        )

    unclassified = [name for name in discovered if not classified(name)]
    print(f"Unclassified public-looking names: {len(unclassified)}")
    for name in unclassified:
        print(name)
    return unclassified


def load_inventory(path: Path) -> ApiInventory:
    """Load and validate a renderer-independent API inventory."""
    if not path.is_file():
        raise DocumentationError(
            f"API inventory does not exist: {path}. Run 'python tools/docs.py inventory'."
        )
    try:
        text = path.read_text(encoding="utf-8")
        data = json.loads(text)
        sections = [
            {
                "id": str(section["id"]),
                "title": str(section["title"]),
                "audience": str(section["audience"]),
            }
            for section in data["sections"]
        ]
        symbols: list[ApiSymbol] = []
        for item in data["symbols"]:
            documentation_data = item["documentation"]
            documentation = DocumentationRecord(
                summary=str(documentation_data.get("summary", "")),
                body=str(documentation_data.get("body", "")),
                parameters={
                    str(name): str(description)
                    for name, description in documentation_data.get("parameters", {}).items()
                },
                returns=str(documentation_data.get("returns", "")),
                raises=[str(value) for value in documentation_data.get("raises", [])],
                status=str(documentation_data["status"]),
            )
            source_data = item.get("source")
            source = (
                SourceReference(
                    path=str(source_data["path"]),
                    line=int(source_data["line"]) if source_data.get("line") is not None else None,
                )
                if source_data is not None
                else None
            )
            symbols.append(
                ApiSymbol(
                    name=str(item["name"]),
                    canonical_name=str(item["canonical_name"]),
                    kind=str(item["kind"]),
                    section=str(item["section"]),
                    audience=str(item["audience"]),
                    signatures=[str(value) for value in item.get("signatures", [])],
                    aliases=[str(value) for value in item.get("aliases", [])],
                    documentation=documentation,
                    source=source,
                )
            )
        inventory = ApiInventory(
            schema_version=int(data["schema_version"]),
            package_version=str(data["package_version"]),
            sections=sections,
            symbols=symbols,
        )
    except (AttributeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise DocumentationError(f"Invalid API inventory: {path}") from exc

    if inventory.schema_version != 1:
        raise DocumentationError(
            f"Unsupported API inventory schema version: {inventory.schema_version}"
        )
    problems = _inventory_problems(text)
    if problems:
        raise DocumentationError(
            "API inventory contains environment-dependent data: " + ", ".join(problems)
        )
    section_ids = {section["id"] for section in inventory.sections}
    if len(section_ids) != len(inventory.sections):
        raise DocumentationError("API inventory section IDs must be unique")
    for section in inventory.sections:
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", section["id"]):
            raise DocumentationError(
                f"API inventory section ID is not a stable URL slug: {section['id']}"
            )
        if section["audience"] not in {"user", "extension-author"}:
            raise DocumentationError(
                f"API inventory section '{section['id']}' has an unsupported audience"
            )
    symbol_names: set[str] = set()
    for symbol in inventory.symbols:
        if symbol.name in symbol_names:
            raise DocumentationError(f"Duplicate symbol in API inventory: {symbol.name}")
        symbol_names.add(symbol.name)
        if symbol.section not in section_ids:
            raise DocumentationError(
                f"API symbol '{symbol.name}' refers to unknown section '{symbol.section}'"
            )
        if symbol.documentation.status not in {"missing", "placeholder", "summary", "complete"}:
            raise DocumentationError(
                f"API symbol '{symbol.name}' has invalid documentation status "
                f"'{symbol.documentation.status}'"
            )
        if symbol.source is not None:
            source_path = PurePosixPath(symbol.source.path)
            if source_path.is_absolute() or ".." in source_path.parts:
                raise DocumentationError(
                    f"API symbol '{symbol.name}' has a non-relative source path"
                )
    return inventory


def _signature_shape(signature: str) -> tuple[list[str], bool]:
    start = signature.find("(")
    if start < 0:
        return [], False
    depth = 0
    quote = ""
    escaped = False
    end = -1
    for index, character in enumerate(signature[start:], start=start):
        if quote:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == quote:
                quote = ""
            continue
        if character in {'"', "'"}:
            quote = character
        elif character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth == 0:
                end = index
                break
    if end < 0:
        return [], False

    parameters_text = signature[start + 1 : end]
    parts: list[str] = []
    part_start = 0
    nesting = 0
    quote = ""
    escaped = False
    for index, character in enumerate(parameters_text):
        if quote:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == quote:
                quote = ""
            continue
        if character in {'"', "'"}:
            quote = character
        elif character in "([{":
            nesting += 1
        elif character in ")]}":
            nesting -= 1
        elif character == "," and nesting == 0:
            parts.append(parameters_text[part_start:index])
            part_start = index + 1
    parts.append(parameters_text[part_start:])

    parameters: list[str] = []
    for part in parts:
        value = part.strip()
        if not value or value in {"/", "*"}:
            continue
        value = value.lstrip("*")
        name = re.split(r"[:=]", value, maxsplit=1)[0].strip()
        if name and name not in {"self", "cls"}:
            parameters.append(name)

    return_annotation = signature[end + 1 :].strip()
    requires_return = False
    if return_annotation.startswith("->"):
        return_type = return_annotation.removeprefix("->").strip()
        requires_return = return_type not in {"", "None", "NoneType", "typing.NoneType"}
    return list(dict.fromkeys(parameters)), requires_return


def _documentation_has_examples(documentation: DocumentationRecord) -> bool:
    text = "\n".join((documentation.summary, documentation.body)).lower()
    return any(marker in text for marker in ("example:", "examples:", ".. code-block::", ">>>"))


def _coverage_status(symbol: ApiSymbol) -> CoverageSymbol:
    documentation = symbol.documentation
    all_text = [
        documentation.summary,
        documentation.body,
        *documentation.parameters.values(),
        documentation.returns,
        *documentation.raises,
    ]
    has_placeholder = any(value.strip().upper() == "N/A" for value in all_text)
    has_content = any(value.strip() and value.strip().upper() != "N/A" for value in all_text)
    has_summary = bool(
        documentation.summary.strip() and documentation.summary.strip().upper() != "N/A"
    )
    expected_parameters: list[str] = []
    requires_return = False
    for signature in symbol.signatures:
        parameters, signature_requires_return = _signature_shape(signature)
        expected_parameters.extend(parameters)
        requires_return = requires_return or signature_requires_return
    expected_parameters = list(dict.fromkeys(expected_parameters))
    documented_parameters = {
        name.split()[-1].lstrip("*") for name in documentation.parameters if name.strip()
    }
    missing_parameters = [name for name in expected_parameters if name not in documented_parameters]
    return_documented = bool(
        documentation.returns.strip() and documentation.returns.strip().upper() != "N/A"
    )

    if documentation.status == "placeholder" or (has_placeholder and not has_content):
        status = "placeholder"
    elif not has_content:
        status = "missing"
    elif has_summary and not missing_parameters and (not requires_return or return_documented):
        status = "complete"
    else:
        status = "summary"

    return CoverageSymbol(
        name=symbol.name,
        status=status,
        missing_parameters=missing_parameters,
        requires_return=requires_return,
        return_documented=return_documented,
        has_examples=_documentation_has_examples(documentation),
    )


def calculate_coverage(inventory: ApiInventory) -> CoverageReport:
    """Calculate mechanical documentation coverage for every public symbol."""
    symbols = [_coverage_status(symbol) for symbol in inventory.symbols]
    counts = {
        status: sum(symbol.status == status for symbol in symbols)
        for status in ("missing", "placeholder", "summary", "complete")
    }
    score_weights = {"missing": 0, "placeholder": 0, "summary": 1, "complete": 2}
    return CoverageReport(
        schema_version=1,
        package_version=inventory.package_version,
        counts=counts,
        documented=counts["summary"] + counts["complete"],
        score=sum(score_weights[symbol.status] for symbol in symbols),
        symbols=symbols,
    )


def _coverage_text(report: CoverageReport) -> str:
    return json.dumps(asdict(report), indent=2, ensure_ascii=True) + "\n"


def write_coverage_report(report: CoverageReport, output: Path) -> None:
    """Write a deterministic documentation coverage report."""
    text = _coverage_text(report)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.is_file() or output.read_text(encoding="utf-8") != text:
        output.write_text(text, encoding="utf-8")


def load_coverage_report(path: Path) -> CoverageReport:
    """Load a checked-in documentation coverage baseline."""
    if not path.is_file():
        raise DocumentationError(
            f"Coverage baseline does not exist: {path}. Review and write an initial baseline."
        )
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        report = CoverageReport(
            schema_version=int(data["schema_version"]),
            package_version=str(data["package_version"]),
            counts={str(name): int(value) for name, value in data["counts"].items()},
            documented=int(data["documented"]),
            score=int(data["score"]),
            symbols=[
                CoverageSymbol(
                    name=str(symbol["name"]),
                    status=str(symbol["status"]),
                    missing_parameters=[str(name) for name in symbol.get("missing_parameters", [])],
                    requires_return=bool(symbol.get("requires_return", False)),
                    return_documented=bool(symbol.get("return_documented", False)),
                    has_examples=bool(symbol.get("has_examples", False)),
                )
                for symbol in data["symbols"]
            ],
        )
    except (AttributeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise DocumentationError(f"Invalid coverage baseline: {path}") from exc
    if report.schema_version != 1:
        raise DocumentationError(
            f"Unsupported coverage baseline schema version: {report.schema_version}"
        )
    if set(report.counts) != {"missing", "placeholder", "summary", "complete"}:
        raise DocumentationError("Coverage baseline has invalid status counts")
    if len({symbol.name for symbol in report.symbols}) != len(report.symbols):
        raise DocumentationError("Coverage baseline contains duplicate symbols")
    return report


def validate_coverage(report: CoverageReport, baseline: Path) -> None:
    """Validate current documentation coverage against a reviewed baseline."""
    expected = load_coverage_report(baseline)
    current_by_name = {symbol.name: symbol for symbol in report.symbols}
    expected_by_name = {symbol.name: symbol for symbol in expected.symbols}
    problems: list[str] = []

    if report.documented < expected.documented:
        problems.append(
            f"documented symbol count decreased from {expected.documented} to "
            f"{report.documented}"
        )
    if report.score < expected.score:
        problems.append(f"coverage score decreased from {expected.score} to {report.score}")

    removed = sorted(set(expected_by_name) - set(current_by_name))
    if removed:
        problems.append("baseline symbols were removed: " + ", ".join(removed))

    regressed_complete = sorted(
        name
        for name, symbol in expected_by_name.items()
        if symbol.status == "complete"
        and name in current_by_name
        and current_by_name[name].status != "complete"
    )
    if regressed_complete:
        problems.append("completed symbols regressed: " + ", ".join(regressed_complete))

    new_undocumented = sorted(
        name
        for name, symbol in current_by_name.items()
        if name not in expected_by_name and symbol.status in {"missing", "placeholder"}
    )
    if new_undocumented:
        problems.append("new public symbols are undocumented: " + ", ".join(new_undocumented))

    new_placeholders = sorted(
        name
        for name, symbol in current_by_name.items()
        if symbol.status == "placeholder"
        and (name not in expected_by_name or expected_by_name[name].status != "placeholder")
    )
    if new_placeholders:
        problems.append("new placeholders were added: " + ", ".join(new_placeholders))

    if problems:
        details = "\n".join(f"  - {problem}" for problem in problems)
        raise DocumentationError(f"Documentation coverage regressed:\n{details}")


def coverage_command(
    inventory_path: Path,
    baseline_path: Path,
    check: bool,
    output: Path | None,
) -> None:
    """Report or validate documentation coverage for the API inventory."""
    report = calculate_coverage(load_inventory(inventory_path))
    if output is not None:
        write_coverage_report(report, output)
        print(f"Wrote coverage report to {output}")
    if check:
        validate_coverage(report, baseline_path)
        action = "Validated"
    else:
        action = "Calculated"
    counts = report.counts
    print(
        f"{action} documentation coverage for {len(report.symbols)} symbols: "
        f"{counts['complete']} complete, {counts['summary']} summary, "
        f"{counts['missing']} missing, {counts['placeholder']} placeholder, "
        f"score {report.score}"
    )


def prepare_agent_site_assets(
    inventory_path: Path = API_INVENTORY_PATH,
    output_dir: Path = AGENT_SITE_SOURCE_DIR,
) -> None:
    """Prepare versioned API and coverage JSON for publication with the site."""
    inventory = load_inventory(inventory_path)
    coverage = calculate_coverage(inventory)
    api_dir = output_dir / "api"
    write_inventory(inventory, api_dir / "api.json")
    write_coverage_report(coverage, api_dir / "coverage.json")
    print(f"Prepared agent API assets in {api_dir}")


def _coverage_missing_fields(symbol: CoverageSymbol) -> list[str]:
    fields: list[str] = []
    if symbol.status == "missing":
        fields.append("summary")
    elif symbol.status == "placeholder":
        fields.append("replace placeholder")
    if symbol.missing_parameters:
        fields.append("parameters: " + ", ".join(symbol.missing_parameters))
    if symbol.requires_return and not symbol.return_documented:
        fields.append("return value")
    if not symbol.has_examples:
        fields.append("example")
    return fields


def _search_terms(symbol: ApiSymbol) -> list[str]:
    parts = symbol.name.split(".")
    package_relative = ".".join(parts[1:])
    terms = [symbol.name, f"spy.{package_relative}", package_relative]
    if len(parts) >= 3:
        terms.append(".".join(parts[-2:]))
    terms.append(parts[-1])
    return list(dict.fromkeys(term for term in terms if len(term) >= 3))


def _search_repository(
    repository_root: Path,
    roots: Sequence[str],
    symbol: ApiSymbol,
    limit: int,
) -> list[RepositoryReference]:
    """Find deterministic, bounded repository references for a public symbol."""
    suffixes = {".cpp", ".h", ".hpp", ".ipynb", ".md", ".py", ".rst", ".slang"}
    terms = _search_terms(symbol)
    leaf = symbol.name.rsplit(".", 1)[-1]
    declaration_re = re.compile(
        rf"^\s*(?:class|struct|enum(?:\s+class)?)\s+(?:\w+\s+)*{re.escape(leaf)}\b"
    )
    binding_class_re = re.compile(rf"\bnb::class_<[^>]*\b{re.escape(leaf)}\b")
    matches: list[tuple[int, RepositoryReference]] = []
    for relative_root in roots:
        search_root = repository_root / relative_root
        if not search_root.is_dir():
            continue
        for path in sorted(search_root.rglob("*")):
            if (
                not path.is_file()
                or path.suffix.lower() not in suffixes
                or path.name == "py_doc.h"
                or (repository_root / "slangpy" / "tests" / "docs") in path.parents
                or path.stat().st_size > 5_000_000
            ):
                continue
            try:
                lines = path.read_text(encoding="utf-8").splitlines()
            except UnicodeDecodeError:
                continue
            best: tuple[int, int] | None = None
            for line_number, line in enumerate(lines, start=1):
                score = 0
                for index, term in enumerate(terms):
                    if term in line:
                        score = max(score, 100 - index * 10)
                if f'.def("{leaf}"' in line or f'.def_prop_ro("{leaf}"' in line:
                    score += 50
                if declaration_re.search(line):
                    score += 100
                if binding_class_re.search(line):
                    score += 100
                if score and (best is None or score > best[0]):
                    best = (score, line_number)
            if best is not None:
                relative = path.resolve().relative_to(repository_root.resolve()).as_posix()
                matches.append((best[0], RepositoryReference(relative, best[1])))
    matches.sort(key=lambda item: (-item[0], item[1].path, item[1].line))
    return [reference for _score, reference in matches[:limit]]


def _reference_link(reference: RepositoryReference | SourceReference) -> str:
    line = reference.line
    label = reference.path if line is None else f"{reference.path}:{line}"
    target = reference.path if line is None else f"{reference.path}#L{line}"
    return f"[{label}]({target.replace(' ', '%20')})"


def _related_symbols(inventory: ApiInventory, symbol: ApiSymbol, limit: int = 24) -> list[str]:
    related: list[str] = []
    names = {candidate.name for candidate in inventory.symbols}
    parent = symbol.name.rsplit(".", 1)[0]
    if parent in names:
        related.append(parent)
    prefix = f"{symbol.name}."
    related.extend(
        candidate.name
        for candidate in inventory.symbols
        if candidate.name.startswith(prefix) and "." not in candidate.name[len(prefix) :]
    )
    related.extend(symbol.aliases)
    for candidate in inventory.symbols:
        if candidate.name != symbol.name and candidate.canonical_name == symbol.canonical_name:
            related.append(candidate.name)
    fields = [
        symbol.documentation.summary,
        symbol.documentation.body,
        *symbol.documentation.parameters.values(),
        symbol.documentation.returns,
        *symbol.documentation.raises,
    ]
    for text_value in fields:
        for match in INTERNAL_PYTHON_REFERENCE_RE.finditer(text_value):
            target = match.group(1).strip().lstrip("~")
            titled_target = re.search(r"<([^>]+)>$", target)
            if titled_target:
                target = titled_target.group(1).strip().lstrip("~")
            if target in names:
                related.append(target)
    return list(dict.fromkeys(related))[:limit]


def generate_context(
    inventory: ApiInventory,
    symbol_name: str,
    repository_root: Path,
) -> str:
    """Generate a bounded Markdown context package for one public symbol."""
    symbols = {symbol.name: symbol for symbol in inventory.symbols}
    symbol = symbols.get(symbol_name)
    if symbol is None:
        raise DocumentationError(f"Public API symbol was not found: {symbol_name}")
    coverage_by_name = {
        coverage.name: coverage for coverage in calculate_coverage(inventory).symbols
    }
    coverage = coverage_by_name[symbol.name]
    native_backed = symbol.source is None or symbol.source.path.endswith(".pyi")
    declarations = (
        _search_repository(repository_root, ("src/sgl",), symbol, 8) if native_backed else []
    )
    bindings = (
        _search_repository(repository_root, ("src/slangpy_ext",), symbol, 8)
        if native_backed
        else []
    )
    tests = _search_repository(
        repository_root,
        ("slangpy/tests", "tests", "samples/tests"),
        symbol,
        12,
    )
    examples = _search_repository(
        repository_root,
        ("samples/tutorials", "samples/examples", "samples/experiments", "examples", "docs/src"),
        symbol,
        12,
    )
    related = _related_symbols(inventory, symbol)

    lines = [
        "<!-- schema_version: 1 -->",
        "",
        f"# Documentation context: `{symbol.name}`",
        "",
        f"- **Kind:** `{symbol.kind}`",
        f"- **Section:** `{symbol.section}`",
        f"- **Audience:** `{symbol.audience}`",
        f"- **Canonical name:** `{symbol.canonical_name}`",
        f"- **Coverage status:** `{coverage.status}`",
        "",
        "## Signatures",
        "",
    ]
    if symbol.signatures:
        lines.extend(["```python", *symbol.signatures, "```"])
    else:
        lines.append("No signature metadata is available.")

    documentation = symbol.documentation
    lines.extend(["", "## Existing documentation", ""])
    if documentation.summary and documentation.summary.upper() != "N/A":
        lines.extend([documentation.summary, ""])
    else:
        lines.extend(["No summary is documented.", ""])
    if documentation.body:
        lines.extend([documentation.body, ""])
    if documentation.parameters:
        lines.extend(["### Parameters", ""])
        lines.extend(
            f"- `{name}`: {description or 'No description.'}"
            for name, description in documentation.parameters.items()
        )
        lines.append("")
    if documentation.returns:
        lines.extend(["### Returns", "", documentation.returns, ""])
    if documentation.raises:
        lines.extend(["### Raises", ""])
        lines.extend(f"- {raised}" for raised in documentation.raises)
        lines.append("")

    missing_fields = _coverage_missing_fields(coverage)
    lines.extend(["## Documentation gaps", ""])
    if missing_fields:
        lines.extend(f"- {field}" for field in missing_fields)
    else:
        lines.append("No mechanically detectable gaps.")

    lines.extend(["", "## Canonical source", ""])
    if symbol.source is not None:
        lines.append(f"- {_reference_link(symbol.source)}")
    else:
        lines.append("No source location is present in the static inventory.")

    def add_references(title: str, references: Sequence[RepositoryReference]) -> None:
        lines.extend(["", f"## {title}", ""])
        if references:
            lines.extend(f"- {_reference_link(reference)}" for reference in references)
        else:
            lines.append("None found by deterministic repository search.")

    add_references("Native declarations", declarations)
    add_references("Python binding locations", bindings)
    lines.extend(["", "## Related public symbols", ""])
    if related:
        lines.extend(f"- `{name}`" for name in related)
    else:
        lines.append("None identified.")
    add_references("Relevant tests", tests)
    add_references("Examples and narrative documentation", examples)
    lines.extend(
        [
            "",
            "## Authoring constraints",
            "",
            "Edit authoritative Python docstrings or C++ documentation comments, not generated files.",
            "Confirm behavioral claims in implementation or tests and keep examples executable or explicitly illustrative.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_print(text_value: str, output: Path | None) -> None:
    if output is None:
        print(text_value, end="")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.is_file() or output.read_text(encoding="utf-8") != text_value:
        output.write_text(text_value, encoding="utf-8")


def context_command(
    symbol_name: str,
    inventory_path: Path,
    repository_root: Path,
    output: Path | None,
) -> None:
    """Write or print an agent context package for one public symbol."""
    text_value = generate_context(load_inventory(inventory_path), symbol_name, repository_root)
    _write_or_print(text_value, output)


def _configured_roots(
    section: PublicApiSection,
    inventory: ApiInventory,
) -> list[str]:
    roots = list(section.names)
    section_names = [symbol.name for symbol in inventory.symbols if symbol.section == section.id]
    for pattern in section.patterns:
        roots.extend(name for name in section_names if re.fullmatch(pattern, name))
    return list(dict.fromkeys(roots))


def calculate_documentation_tasks(
    inventory: ApiInventory,
    config: PublicApiConfig,
    section_id: str | None = None,
) -> list[DocumentationTask]:
    """Return incomplete documentation ordered by API priority then status."""
    section_priorities = {section.id: index for index, section in enumerate(config.sections)}
    if section_id is not None and section_id not in section_priorities:
        raise DocumentationError(f"Unknown public API section: {section_id}")
    roots_by_section = {
        section.id: _configured_roots(section, inventory) for section in config.sections
    }
    coverage_by_name = {symbol.name: symbol for symbol in calculate_coverage(inventory).symbols}
    status_priorities = {"missing": 0, "placeholder": 1, "summary": 2}
    indexed_tasks: list[tuple[tuple[int, int, int, str], DocumentationTask]] = []
    for symbol in inventory.symbols:
        coverage = coverage_by_name[symbol.name]
        if coverage.status == "complete" or (
            section_id is not None and symbol.section != section_id
        ):
            continue
        roots = roots_by_section[symbol.section]
        root_priority = len(roots)
        for index, root in enumerate(roots):
            if symbol.name == root or symbol.name.startswith(f"{root}."):
                root_priority = index
                break
        task = DocumentationTask(
            name=symbol.name,
            section=symbol.section,
            audience=symbol.audience,
            status=coverage.status,
            missing_fields=_coverage_missing_fields(coverage),
            source=symbol.source,
        )
        priority = (
            section_priorities[symbol.section],
            root_priority,
            status_priorities[coverage.status],
            symbol.name,
        )
        indexed_tasks.append((priority, task))
    return [task for _priority, task in sorted(indexed_tasks, key=lambda item: item[0])]


def _tasks_json(
    inventory: ApiInventory,
    tasks: Sequence[DocumentationTask],
    section_id: str | None,
) -> str:
    data = {
        "schema_version": 1,
        "package_version": inventory.package_version,
        "section": section_id,
        "count": len(tasks),
        "tasks": [asdict(task) for task in tasks],
    }
    return json.dumps(data, indent=2, ensure_ascii=True) + "\n"


def _tasks_markdown(
    inventory: ApiInventory,
    tasks: Sequence[DocumentationTask],
    section_id: str | None,
) -> str:
    scope = f"section `{section_id}`" if section_id is not None else "all reviewed sections"
    lines = [
        "<!-- schema_version: 1 -->",
        "",
        "# SlangPy documentation tasks",
        "",
        f"{len(tasks)} incomplete symbols in {scope} for package version `{inventory.package_version}`.",
        "",
    ]
    for task in tasks:
        fields = "; ".join(task.missing_fields) or "review documentation"
        source = f" - {_reference_link(task.source)}" if task.source is not None else ""
        lines.append(f"- [ ] `{task.name}` - **{task.status}** - {fields}{source}")
    return "\n".join(lines).rstrip() + "\n"


def tasks_command(
    inventory_path: Path,
    config_path: Path,
    section_id: str | None,
    output_format: str,
    output: Path | None,
) -> None:
    """Write or print prioritized documentation tasks."""
    inventory = load_inventory(inventory_path)
    config = load_public_api(config_path)
    _validate_render_inputs(inventory, config)
    tasks = calculate_documentation_tasks(inventory, config, section_id)
    if output_format == "json":
        text_value = _tasks_json(inventory, tasks, section_id)
    elif output_format == "markdown":
        text_value = _tasks_markdown(inventory, tasks, section_id)
    else:
        raise DocumentationError(f"Unsupported documentation task format: {output_format}")
    _write_or_print(text_value, output)


INTERNAL_PYTHON_REFERENCE_RE = re.compile(
    r":(?:py:)?(?:attr|class|data|func|meth|obj|property|type):`([^`]+)`"
)


def validate_internal_references(inventory: ApiInventory, package_name: str) -> None:
    """Reject documentation links to unpublished names in the package namespace."""
    public_names = {symbol.name for symbol in inventory.symbols}
    problems: list[str] = []
    for symbol in inventory.symbols:
        documentation = symbol.documentation
        fields = [
            documentation.summary,
            documentation.body,
            *documentation.parameters.values(),
            documentation.returns,
            *documentation.raises,
        ]
        for text in fields:
            for match in INTERNAL_PYTHON_REFERENCE_RE.finditer(text):
                target = match.group(1).strip().lstrip("~")
                titled_target = re.search(r"<([^>]+)>$", target)
                if titled_target:
                    target = titled_target.group(1).strip().lstrip("~")
                if target.startswith(f"{package_name}.") and target not in public_names:
                    problems.append(f"{symbol.name} -> {target}")
    if problems:
        raise DocumentationError(
            "Structured API documentation has broken internal references:\n  - "
            + "\n  - ".join(sorted(set(problems)))
        )


def _validate_render_inputs(inventory: ApiInventory, config: PublicApiConfig) -> None:
    expected_sections = [
        {"id": section.id, "title": section.title, "audience": section.audience}
        for section in config.sections
    ]
    if inventory.sections != expected_sections:
        raise DocumentationError(
            "API inventory sections do not match docs/public_api.toml. " "Regenerate the inventory."
        )
    symbol_names = {symbol.name for symbol in inventory.symbols}
    missing = [
        name for section in config.sections for name in section.names if name not in symbol_names
    ]
    if missing:
        raise DocumentationError(
            "API inventory is missing reviewed public names: " + ", ".join(missing)
        )
    section_audiences = {section.id: section.audience for section in config.sections}
    for symbol in inventory.symbols:
        expected_audience = section_audiences.get(symbol.section)
        if symbol.audience != expected_audience:
            raise DocumentationError(
                f"API symbol '{symbol.name}' has audience '{symbol.audience}', expected "
                f"'{expected_audience}'"
            )
    validate_internal_references(inventory, config.package)


def _api_anchor(name: str) -> str:
    return "api-" + re.sub(r"[^a-z0-9_]+", "-", name.lower()).strip("-")


def _api_anchors(symbols: Sequence[ApiSymbol]) -> dict[str, str]:
    """Return stable anchors, disambiguating names that differ only by case."""
    names_by_anchor: dict[str, list[str]] = {}
    for symbol in symbols:
        names_by_anchor.setdefault(_api_anchor(symbol.name), []).append(symbol.name)

    anchors: dict[str, str] = {}
    for base_anchor, names in names_by_anchor.items():
        if len(names) == 1:
            anchors[names[0]] = base_anchor
            continue
        for name in sorted(names):
            digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:8]
            anchors[name] = f"{base_anchor}-{digest}"
    return anchors


def _directive_for_kind(kind: str) -> str:
    return {
        "attribute": "attribute",
        "class": "class",
        "classmethod": "classmethod",
        "constructor": "method",
        "data": "data",
        "enum": "class",
        "enum-member": "attribute",
        "function": "function",
        "method": "method",
        "property": "property",
        "staticmethod": "staticmethod",
    }.get(kind, "object")


def _indent_rst(text: str, indentation: str = "   ") -> list[str]:
    safe_lines: list[str] = []
    previous_indent = 0
    previous_blank = True
    for raw_line in text.replace("*", r"\*").splitlines():
        current_indent = len(raw_line) - len(raw_line.lstrip())
        if not previous_blank and current_indent != previous_indent:
            safe_lines.append("")
        safe_lines.append(raw_line)
        previous_indent = current_indent
        previous_blank = not raw_line
    return [f"{indentation}{line}" if line else "" for line in safe_lines]


def _safe_documentation_text(text: str) -> str:
    if text.strip().upper() == "N/A":
        return ""
    return text.replace("*", r"\*")


def _render_symbol(
    symbol: ApiSymbol,
    anchor: str,
    class_names: set[str],
    show_missing_documentation: bool,
) -> list[str]:
    lines = [f".. _{anchor}:", ""]
    if symbol.kind in {"class", "enum"}:
        title = symbol.name.rsplit(".", 1)[-1]
        lines.extend([title, "-" * len(title), ""])

    directive = _directive_for_kind(symbol.kind)
    if directive == "object":
        lines.extend([f".. py:attribute:: {symbol.name}", ""])
    else:
        lines.extend([f".. py:{directive}:: {symbol.name}", ""])

    documentation = symbol.documentation
    if documentation.status in {"missing", "placeholder"}:
        if show_missing_documentation:
            lines.extend(["   *Documentation pending.*", ""])
    else:
        if _safe_documentation_text(documentation.summary):
            lines.extend(_indent_rst(documentation.summary))
            lines.append("")
        if _safe_documentation_text(documentation.body):
            lines.extend(_indent_rst(documentation.body))
            lines.append("")

    if symbol.signatures:
        heading = "Overloads" if len(symbol.signatures) > 1 else "Signature"
        lines.extend([f"   **{heading}**", "", "   .. code-block:: python", ""])
        for signature in symbol.signatures:
            lines.append(f"      {signature}")
        lines.append("")

    if documentation.status not in {"missing", "placeholder"}:
        if documentation.parameters:
            lines.extend(["   **Parameters**", ""])
            for name, description in documentation.parameters.items():
                description = _safe_documentation_text(description)
                if description:
                    lines.append(f"   * ``{name}`` -- {description}")
            lines.append("")
        if _safe_documentation_text(documentation.returns):
            lines.extend(["   **Returns:**", ""])
            lines.extend(_indent_rst(documentation.returns))
            lines.append("")
        if documentation.raises:
            lines.extend(["   **Raises**", ""])
            for raised in documentation.raises:
                raised = _safe_documentation_text(raised)
                if raised:
                    lines.append(f"   * {raised}")
            lines.append("")

    parent_name = symbol.name.rsplit(".", 1)[0]
    if parent_name in class_names:
        lines.extend([f"   **Member of:** :py:class:`~{parent_name}`", ""])
    if symbol.aliases:
        aliases = ", ".join(f":py:obj:`{alias}`" for alias in symbol.aliases)
        lines.extend([f"   **Aliases:** {aliases}", ""])
    if symbol.canonical_name != symbol.name:
        lines.extend([f"   **Canonical implementation:** ``{symbol.canonical_name}``", ""])
    if symbol.source is not None:
        location = symbol.source.path
        if symbol.source.line is not None:
            location += f":{symbol.source.line}"
        lines.extend([f"   **Source:** ``{location}``", ""])
    return lines


def _render_section(
    section: dict[str, str],
    symbols: list[ApiSymbol],
    anchors: dict[str, str],
    show_missing_documentation: bool,
) -> str:
    title = section["title"]
    audience = "Primary users" if section["audience"] == "user" else "Extension authors"
    lines = [
        GENERATED_PAGE_HEADER,
        "",
        f".. _api-section-{section['id']}:",
        "",
        title,
        "=" * len(title),
        "",
        f"**Audience:** {audience}",
        "",
    ]
    class_names = {symbol.name for symbol in symbols if symbol.kind in {"class", "enum"}}
    for symbol in symbols:
        lines.extend(
            _render_symbol(
                symbol,
                anchors[symbol.name],
                class_names,
                show_missing_documentation,
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def render_sphinx(
    inventory: ApiInventory,
    output_dir: Path,
    show_missing_documentation: bool = False,
) -> None:
    """Render deterministic Sphinx pages from a structured API inventory."""
    resolved_output = output_dir.resolve()
    protected_directories = {
        Path(resolved_output.anchor),
        PROJECT_DIR.resolve(),
        DOCS_DIR.resolve(),
        (DOCS_DIR / "generated").resolve(),
    }
    if resolved_output in protected_directories:
        raise DocumentationError(
            f"Refusing to render API pages into protected directory: {output_dir}"
        )

    anchors = _api_anchors(inventory.symbols)
    if len(set(anchors.values())) != len(anchors):
        raise DocumentationError("API symbols have duplicate stable anchors")
    for section in inventory.sections:
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", section["id"]):
            raise DocumentationError(
                f"API inventory section ID is not a stable URL slug: {section['id']}"
            )

    output_dir.mkdir(parents=True, exist_ok=True)
    expected_paths: set[Path] = set()
    for section in inventory.sections:
        output_path = output_dir / f"{section['id']}.rst"
        expected_paths.add(output_path.resolve())
        symbols = [symbol for symbol in inventory.symbols if symbol.section == section["id"]]
        text = _render_section(section, symbols, anchors, show_missing_documentation)
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != text:
            output_path.write_text(text, encoding="utf-8")
    for stale_path in output_dir.glob("*.rst"):
        if stale_path.resolve() not in expected_paths and stale_path.read_text(
            encoding="utf-8"
        ).startswith(GENERATED_PAGE_HEADER):
            stale_path.unlink()


def render_command(inventory_path: Path, config_path: Path, output_dir: Path) -> None:
    """Load, validate, and render the checked-in structured API snapshot."""
    config = load_public_api(config_path)
    inventory = load_inventory(inventory_path)
    _validate_render_inputs(inventory, config)
    render_sphinx(inventory, output_dir, config.show_missing_documentation)
    print(
        f"Rendered {len(inventory.sections)} structured API pages with "
        f"{len(inventory.symbols)} symbols in {output_dir}"
    )


def prepare_tutorials(
    source_dir: Path = TUTORIAL_SOURCE_DIR,
    output_dir: Path = TUTORIAL_OUTPUT_DIR,
) -> None:
    """Copy tutorial sources into the generated Sphinx source directory."""
    if not source_dir.is_dir():
        raise DocumentationError(f"Tutorial source directory does not exist: {source_dir}")

    resolved_output = output_dir.resolve()
    protected_directories = {
        Path(resolved_output.anchor),
        PROJECT_DIR.resolve(),
        DOCS_DIR.resolve(),
        source_dir.resolve(),
    }
    if resolved_output in protected_directories:
        raise DocumentationError(f"Refusing to replace protected directory: {output_dir}")

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_dir, output_dir)
    print(f"Prepared tutorials in {output_dir}")


def generate_legacy_api() -> None:
    """Generate the legacy API snapshot from a built SlangPy module."""
    sys.path.insert(0, str(PROJECT_DIR))
    sys.path.insert(0, str(DOCS_DIR))
    try:
        importlib.import_module("slangpy")
        generate_api_module = importlib.import_module("generate_api")
        generate_api_module.generate_api()
    except (Exception, SystemExit) as exc:
        raise DocumentationError(
            "Could not import the built SlangPy package to generate API documentation. "
            "Build SlangPy before running documentation validation, or use "
            "'prepare --api-mode snapshot' for an explicit source-only build."
        ) from exc
    finally:
        sys.path.remove(str(DOCS_DIR))
        sys.path.remove(str(PROJECT_DIR))

    print(f"Generated legacy API snapshot at {GENERATED_API_PATH}")


def find_generated_api_problems(text: str) -> list[str]:
    """Return unstable or machine-dependent content found in generated API text."""
    problems: list[str] = []
    for name in sorted(FORBIDDEN_DATA_NAMES):
        if f".. py:data:: {name}" in text:
            problems.append(f"forbidden runtime data entry: {name}")

    for line_number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith(".. py:data::"):
            name = stripped.removeprefix(".. py:data::").strip()
            if name not in ALLOWED_DATA_NAMES:
                problems.append(f"line {line_number}: unapproved runtime data entry: {name}")
        if (
            WINDOWS_ABSOLUTE_PATH_RE.search(stripped)
            or POSIX_ABSOLUTE_PATH_RE.search(stripped)
            or BUILD_PATH_RE.search(stripped)
        ):
            problems.append(f"line {line_number}: absolute or build path in generated value")
        if "local changes" in stripped.lower() or "branch:" in stripped.lower():
            problems.append(f"line {line_number}: local Git description in generated value")
        if MEMORY_ADDRESS_RE.search(stripped):
            problems.append(f"line {line_number}: memory address in generated value")
        if stripped.startswith(":value:"):
            value = stripped.removeprefix(":value:").strip()
        else:
            value = ""
        if value.startswith("<") and value.endswith(">"):
            problems.append(
                f"line {line_number}: unstable object representation in generated value"
            )

    return problems


def check_generated_api(path: Path = GENERATED_API_PATH) -> None:
    """Validate that the generated API snapshot exists and is reproducible."""
    if not path.is_file():
        raise DocumentationError(
            f"Generated API snapshot does not exist: {path}. "
            "Run 'python tools/docs.py prepare --api-mode runtime' after building SlangPy."
        )

    problems = find_generated_api_problems(path.read_text(encoding="utf-8"))
    if problems:
        details = "\n".join(f"  - {problem}" for problem in problems)
        raise DocumentationError(f"Generated API snapshot is not reproducible:\n{details}")

    print(f"Validated generated API snapshot at {path}")


def _curated_llms_text() -> str:
    lines = [
        "# SlangPy",
        "",
        "> SlangPy is a Python interface for GPU programming with Slang, including automatic data marshalling, differentiation, and low-level graphics APIs.",
    ]
    for heading, pages in CURATED_LLMS_PAGES:
        lines.extend(["", f"## {heading}", ""])
        lines.extend(f"- [{title}]({path}): {description}" for title, path, description in pages)
    return "\n".join(lines).rstrip() + "\n"


def write_curated_llms(output_dir: Path) -> None:
    """Replace the generated sitemap with SlangPy's reviewed agent index."""
    _write_or_print(_curated_llms_text(), output_dir / "llms.txt")


def validate_agent_outputs(output_dir: Path) -> None:
    """Validate Markdown and machine-readable artifacts produced by an HTML build."""
    missing_markdown: list[str] = []
    source_paths = [
        path
        for path in DOCS_DIR.rglob("*.rst")
        if DOCS_DIR / "_build" not in path.parents and path != GENERATED_API_PATH
    ]
    source_paths.extend(
        path for path in (DOCS_DIR / "src" / "tutorials").glob("*.ipynb") if path.is_file()
    )
    for source_path in source_paths:
        relative = source_path.relative_to(DOCS_DIR).with_suffix(".md")
        if not (output_dir / relative).is_file():
            missing_markdown.append(relative.as_posix())
    if missing_markdown:
        raise DocumentationError(
            "Agent Markdown output is missing pages: " + ", ".join(sorted(missing_markdown))
        )

    representatives = {
        "src/basics/firstfunctions.md": ("# Your First Function", "```"),
        "generated/api/device.md": ("# Device", "slangpy.Device", "```python", "**Source:**"),
        "generated/api/functional-api.md": (
            "# Functional API",
            "slangpy.Module",
            "```python",
            "](#",
        ),
        "src/tutorials/compute_shader.md": ("# Compute Shader", "```c#"),
    }
    for relative, expected_values in representatives.items():
        text_value = (output_dir / relative).read_text(encoding="utf-8")
        missing_values = [value for value in expected_values if value not in text_value]
        if missing_values:
            raise DocumentationError(
                f"Agent Markdown page '{relative}' lost expected content: "
                + ", ".join(missing_values)
            )
        if "<nav" in text_value.lower():
            raise DocumentationError(f"Agent Markdown page contains HTML navigation: {relative}")

    llms_path = output_dir / "llms.txt"
    if not llms_path.is_file() or llms_path.read_text(encoding="utf-8") != _curated_llms_text():
        raise DocumentationError("llms.txt is missing or does not match the curated index")
    if (output_dir / "llms-full.txt").exists():
        raise DocumentationError("llms-full.txt must remain disabled for the expanded API")

    published_inventory = output_dir / "api" / "api.json"
    published_coverage = output_dir / "api" / "coverage.json"
    if not published_inventory.is_file() or not published_coverage.is_file():
        raise DocumentationError("Published agent API JSON files are missing")
    inventory = load_inventory(published_inventory)
    coverage = load_coverage_report(published_coverage)
    if coverage.package_version != inventory.package_version:
        raise DocumentationError("Published API and coverage versions do not match")
    if len(coverage.symbols) != len(inventory.symbols):
        raise DocumentationError("Published API and coverage symbol counts do not match")
    print(f"Validated {len(source_paths)} Markdown pages, curated llms.txt, and agent API JSON")


def prepare(api_mode: str) -> None:
    """Prepare tutorials and the selected API input for a Sphinx build."""
    prepare_tutorials()
    if api_mode == "runtime":
        print("API mode: runtime (regenerating from the built SlangPy package)")
        generate_legacy_api()
    elif api_mode == "snapshot":
        print("API mode: snapshot (using the checked-in generated API)")
    else:
        raise DocumentationError(f"Unsupported API mode: {api_mode}")
    check_generated_api()
    render_command(API_INVENTORY_PATH, PUBLIC_API_PATH, RENDERED_API_DIR)
    coverage_command(
        API_INVENTORY_PATH,
        API_COVERAGE_BASELINE_PATH,
        check=True,
        output=None,
    )
    prepare_agent_site_assets()


def run_sphinx(builder: str, output_dir: Path) -> None:
    """Run a strict Sphinx build."""
    environment = os.environ.copy()
    if shutil.which("pandoc", path=environment.get("PATH")) is None:
        try:
            pypandoc = importlib.import_module("pypandoc")
            pandoc_path = Path(pypandoc.get_pandoc_path())
        except (ImportError, OSError) as exc:
            raise DocumentationError(
                "Pandoc is required to render notebooks. Install docs/requirements.txt."
            ) from exc
        environment["PATH"] = f"{pandoc_path.parent}{os.pathsep}{environment.get('PATH', '')}"

    command = [
        sys.executable,
        "-m",
        "sphinx",
        "-E",
        "-n",
        "-W",
        "--keep-going",
        "-b",
        builder,
        str(DOCS_DIR),
        str(output_dir),
    ]
    print(f'Running "{" ".join(command)}" ...')
    result = subprocess.run(command, cwd=PROJECT_DIR, env=environment, check=False)
    if result.returncode != 0:
        raise DocumentationError(
            f"Sphinx {builder} build failed with exit code {result.returncode}"
        )


def build(api_mode: str, builder: str, output_dir: Path) -> None:
    """Prepare, validate, and build the documentation."""
    prepare(api_mode)
    run_sphinx(builder, output_dir)
    if builder == "html":
        write_curated_llms(output_dir)
        validate_agent_outputs(output_dir)


def create_parser() -> argparse.ArgumentParser:
    """Create the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)

    inventory_parser = commands.add_parser(
        "inventory", help="generate or validate the structured public API inventory"
    )
    inventory_parser.add_argument(
        "--config", type=Path, default=PUBLIC_API_PATH, help="public API TOML contract"
    )
    inventory_parser.add_argument(
        "--package-root", type=Path, default=PROJECT_DIR / "slangpy", help="package directory"
    )
    inventory_parser.add_argument(
        "--output", type=Path, default=API_INVENTORY_PATH, help="output JSON inventory"
    )
    inventory_parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in inventory is stale"
    )

    unclassified_parser = commands.add_parser(
        "report-unclassified", help="report public-looking names outside the API contract"
    )
    unclassified_parser.add_argument(
        "--config", type=Path, default=PUBLIC_API_PATH, help="public API TOML contract"
    )
    unclassified_parser.add_argument(
        "--package-root", type=Path, default=PROJECT_DIR / "slangpy", help="package directory"
    )

    render_parser = commands.add_parser(
        "render", help="render structured Sphinx API pages from the checked-in inventory"
    )
    render_parser.add_argument(
        "--inventory", type=Path, default=API_INVENTORY_PATH, help="input JSON inventory"
    )
    render_parser.add_argument(
        "--config", type=Path, default=PUBLIC_API_PATH, help="public API TOML contract"
    )
    render_parser.add_argument(
        "--output-dir", type=Path, default=RENDERED_API_DIR, help="generated page directory"
    )

    coverage_parser = commands.add_parser(
        "coverage", help="calculate or validate public API documentation coverage"
    )
    coverage_parser.add_argument(
        "--inventory", type=Path, default=API_INVENTORY_PATH, help="input JSON inventory"
    )
    coverage_parser.add_argument(
        "--baseline",
        type=Path,
        default=API_COVERAGE_BASELINE_PATH,
        help="reviewed coverage baseline",
    )
    coverage_parser.add_argument(
        "--check", action="store_true", help="fail if documentation coverage regresses"
    )
    coverage_parser.add_argument(
        "--output", type=Path, help="write the current deterministic coverage report"
    )

    context_parser = commands.add_parser(
        "context", help="generate a bounded Markdown context package for one public symbol"
    )
    context_parser.add_argument("symbol", help="fully qualified public API symbol")
    context_parser.add_argument(
        "--inventory", type=Path, default=API_INVENTORY_PATH, help="input JSON inventory"
    )
    context_parser.add_argument(
        "--repository-root",
        type=Path,
        default=PROJECT_DIR,
        help="repository root used for relative source discovery",
    )
    context_parser.add_argument("--output", type=Path, help="write Markdown instead of stdout")

    tasks_parser = commands.add_parser(
        "tasks", help="list incomplete public documentation in API priority order"
    )
    tasks_parser.add_argument(
        "--inventory", type=Path, default=API_INVENTORY_PATH, help="input JSON inventory"
    )
    tasks_parser.add_argument(
        "--config", type=Path, default=PUBLIC_API_PATH, help="public API TOML contract"
    )
    tasks_parser.add_argument("--section", help="limit tasks to one public API section ID")
    tasks_parser.add_argument(
        "--format",
        choices=("markdown", "json"),
        default="markdown",
        help="output format",
    )
    tasks_parser.add_argument("--output", type=Path, help="write tasks instead of stdout")

    prepare_parser = commands.add_parser("prepare", help="prepare Sphinx source files")
    prepare_parser.add_argument(
        "--api-mode",
        choices=("runtime", "snapshot"),
        default="runtime",
        help="regenerate API docs from the runtime module or use the checked-in snapshot",
    )

    check_parser = commands.add_parser(
        "check-generated", help="check generated API docs for unstable content"
    )
    check_parser.add_argument(
        "--path", type=Path, default=GENERATED_API_PATH, help="generated API RST file"
    )

    build_parser = commands.add_parser("build", help="prepare and run a strict Sphinx build")
    build_parser.add_argument(
        "--api-mode",
        choices=("runtime", "snapshot"),
        default="runtime",
        help="regenerate API docs from the runtime module or use the checked-in snapshot",
    )
    build_parser.add_argument("--builder", default="html", help="Sphinx builder name")
    build_parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_HTML_OUTPUT_DIR,
        help="Sphinx output directory",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the documentation command-line interface."""
    parser = create_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "inventory":
            inventory_command(args.config, args.package_root, args.output, args.check)
        elif args.command == "report-unclassified":
            report_unclassified(args.config, args.package_root)
        elif args.command == "render":
            render_command(args.inventory, args.config, args.output_dir)
        elif args.command == "coverage":
            coverage_command(args.inventory, args.baseline, args.check, args.output)
        elif args.command == "context":
            context_command(args.symbol, args.inventory, args.repository_root, args.output)
        elif args.command == "tasks":
            tasks_command(
                args.inventory,
                args.config,
                args.section,
                args.format,
                args.output,
            )
        elif args.command == "prepare":
            prepare(args.api_mode)
        elif args.command == "check-generated":
            check_generated_api(args.path)
        elif args.command == "build":
            build(args.api_mode, args.builder, args.output_dir)
        else:
            parser.error(f"Unknown command: {args.command}")
    except DocumentationError as exc:
        print(f"Documentation error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
